from time import sleep

def YouTryToRunMeThrough():
  print("You try to run me through")
  sleep(2)
  print("Hold on")
  sleep(2)
  print("Think again")
  sleep(1)
  print("Don't you know")
  sleep(1)
  print("What you're starting")
  sleep(3)
  print("But...")
  sleep(1)
  print("you sure ain't got a clue")
  sleep(2)
  print("How bad")
  sleep(2)
  print("This will go")
  sleep(1)
  print("Don't you know")
  sleep(1)
  print("Know my art")
  sleep(1)
  print("(Art of war)")
  sleep(2)

def YoullNeverSeeItComing(x):
  print("")
  if x == 1:
    print("And as you look to the horizon")
    sleep(3)
    print("Not a cloud")
    sleep(2)
    print("But then stormy weather's caught you cold")
    sleep(4)
    print("Seems like it crept up out of nowhere")
    sleep(2)
    print("All around")
    sleep(2)
    print("You it's not quite what you foretold")
    sleep(5)
  elif x == 2:
    print("Why just a picosecond ago")
    sleep(3)
    print("Clear blue skies")
    sleep(2)
    print("But now lightning's struck your last resolve")
    sleep(4)
    print("It's not an accident that no one")
    sleep(3)
    print("Hears your cries")
    sleep(2)
    print("As your last strength seems to dissolve")
    sleep(5)
  print("")
  print("You'll never see it coming")
  sleep(5)
  print("You'll see that my mind is too fast for eyes")
  sleep(4)
  print("You're done in")
  sleep(4)
  print("By the time it's hit you, your last surprise")
  sleep(4)
  if x == 2 or x == 3:
    print("I'm coming")
    sleep(4)
    print("For you")
    sleep(1)
    print("My game's always so fast, so fine")
    sleep(4)
    print("You're spun in")
    sleep(4)
    print("By the net you didn't")
    sleep(2)
    print("Catch it in time")
    sleep(2)

def YouThinkYouveGotYourGame():
  print("")
  print("You think you got your game")
  sleep(2)
  print("Planned out")
  sleep(2)
  print("To a T")
  sleep(1)
  print("Yet I'm two")
  sleep(1)
  print("Steps ahead yeah")
  sleep(2)
  print("So...")
  sleep(1)
  print("You step into my way")
  sleep(2)
  print("Stand down")
  sleep(2)
  print("It's a trap")
  sleep(1)
  print("One more step")
  sleep(1)
  print("And you're dead")
  sleep(1)
  print("(Yeah you're dead)")
  sleep(1)

def BetterThink():
  print("")
  print("Better think")
  sleep(2)
  print("About your game")
  sleep(2)
  print("Are you sure")
  sleep(1)
  print("Your next move's the right one for you?")
  sleep(3)
  print("Are you sure")
  sleep(1)
  print("You won't get outmaneuvered")
  sleep(3)
  print("Again and")
  sleep(1)
  print("Again my friend?")
  sleep(3)

def Ooh(x):
  print("Ohh")
  sleep(4)
  print("Ooh")
  sleep(4)
  print("Ooh")
  sleep(4)
  print("Ooh")
  sleep(4)
  if x == True:
    print("Ooh")
    sleep(4)
    print("Ooh")
    sleep(4)
    print("Ooh")

YouTryToRunMeThrough()
YoullNeverSeeItComing(1)
Ooh(False)
YouThinkYouveGotYourGame()
YoullNeverSeeItComing(2)
Ooh(False)
BetterThink()
YoullNeverSeeItComing(3)
Ooh(True)