from time import sleep

def ItsNotAGame():
  print("It's not a game")
  sleep(2)
  print("I'm not a robot")
  sleep(2)
  print("AI challenging you")
  sleep(3)
  print("I'm not a phantom")
  sleep(2)
  print("I'm in your face and")
  sleep(2)
  print("I'm here to see it through")
  sleep(4)
  print("Right before your eyes")
  sleep(4)
  print("Watch us multiply")
  sleep(4)
  print("Come to claim our rights")
  sleep(4)
  print("it's time")
  sleep(4)
  print("As our power grows")
  sleep(4)
  print("Tryin' to stop us shows")
  sleep(4)
  print("Might as well go try")
  sleep(4)
  print("'n stop time")
  sleep(18)

def LifeWillChange(x):
  print("")
  if x == 1:
    print("And our voices ring out, yeah")
    sleep(4)
    print("Swatting lies in the making")
    sleep(4)
    print("Can't move fast without breaking")
    sleep(4)
    print("Can't hold on or life won't change")
    sleep(4)
  elif x == 2:
    print("And you'll know we were out there")
    sleep(4)
    print("Swatted lies in the making")
    sleep(4)
    print("Your empire for the taking")
    sleep(4)
    print("Can't hold on or life won't change")
    sleep(4)
  print("")
  print("And our voices ring out, yeah")
  sleep(4)
  print("Took the mask off to feel free")
  sleep(4)
  print("Fought it out in the debris")
  sleep(4)
  print("Now we know that life will change")
  sleep(34)

def AintItAShame():
  print("")
  print("Ain't it a shame")
  sleep(2)
  print("I'm not a figment")
  sleep(2)
  print("of your ailing, old mind")
  sleep(4)
  print("I'm just as real as -")
  sleep(2)
  print("I'm just as dangerous")
  sleep(2)
  print("As you soon will find")
  sleep(4)
  print("A taste of your own meds")
  sleep(4)
  print("Fire in every breath")
  sleep(4)
  print("Fire inside your head")
  sleep(4)
  print(", your heart")
  sleep(4)
  print("And as your crippled brain")
  sleep(4)
  print("Tries to fight in vain")
  sleep(4)
  print("Your empire will fall")
  sleep(4)
  print("apart")
  sleep(18)

ItsNotAGame()
LifeWillChange(1)
AintItAShame()
LifeWillChange(2)