from termcolor import colored

print(colored(""",..,,.,,,,,;;;;;;;;;;;;;;;;;;:,,,,,,::,,,:;i*nxxMMMMMxxxxxxnnz##+++++*****iiii**i::::;;;;;;;:,,,,,,:,,,,,,:,,:::::::::;iiiiiiii;::::;ii;;:::::;:;iii;;
,,,,,,,,:,:;;;;;;;;;;;;;;;;;;:,,,,,,,,,,:;ii*nxxMMMMMxxxxxxnnz###++++*******i***i;:::::;;;;::,,,,,,:,,,:,,::,::,:::::;iiiiiiiii;:::;iii;;:::::::;iii;;
......,,,::;;;;;;;;;;;;;;;;;;:,,,,,,,,:;;;ii*nxxMMMMMxxxxxxxnz###++++********i*ii;:::::;;;;::,,,,,:::,::::::::::::::;iiiiiiiiiii::;iiii;;:;;::::;;;iii
.......,::;;;;;;;;;;:,,,:;;;;::,,,,:,,:;;;;i+nxxMMMMMxxxxxxxnz###++++***********i;:,:;;;;;;::,,,,,,::,:::::::::::::;;iiiiiiiiiii;;iiiii;;:;:::::;;;;ii
,.,,,,,,:;;;;;;;;;;;:,,,,,:;;;;::,,,,,:;;;;i#nxxMMMMMxxxxxxnzz####++++######+***+*::;;;;;;;;;::,,,,::,::::::,::,,::::;iiiiiiiiiiiiii;iii;;::::::;;::;i
,.,,,,,,:;;;;;;;;;;;;,,,,,,;;;;;;:,,,:;;;;;*zxxxMMMMMxxxxxxnz#########++++###+*+#*::;;;;;;;;;::,,,,::,:::::,,,:,,::::;iiiiiiiiiiiii;:;iiii;:;::::;:;;i
......,,::;;;;;::;;;;:,,,,,:;;;;;::,,:;;;;;izxxxxxMMMxxxxxnnz#######+++++++++**#*;::;;;;;;;;;:::::::::::::::::::::::::;iiiiiiiiiii;;:;iiii;::::::;;;ii
......,,,,:;;;::,:;;;;:,,,,:;;;;;;;;:;;;;::izxxxxxxnnxxxxxnnz###++++++##z#+*+**#*;;;;;;;;;;;;;:,,,::::::::::::::::::;;;iiiiiiiiiii;:::;iii;::::;iiiiii
,,,,,,,,:,:;;;:,,,:;;;:,,,,:;;;;;;;;;;;::,,;#nxxxz#+##znxxnnz##+++++*+++*****+**iiiii;;;;;;;;;;;:::::,:,,,:,,::,,:::::;iiiiiiiiiii;:::;iiii;:::;iiiii;
,,,,,,,,:,:;;;:,,,:;;;;::,:;;:::;;;;;;;:,,,:+nxxn######znnnzz##++++*********++**iiiii;;::::;;ii;;;;;::::,:::,::,,::::;iiiiiiiiiii;:::::;iii;;;;iiiiii;
..,,.,,,,,:;;;:,,,:;;;;;:::;;:::,:;;;;;:,,,:*znxz##++###zzzz###++++**********++*iii;;:,,::,:;;iiiii;;:::::::::::::::;iiiiiiiiiii;:::::,:;iiiiiiiiiiii;
..,,.,,,,,:;;;:,,,:;;;;;;;;;;:,,,::;;;;:,,,,;#nxz##++############+++*********+++*ii;::,,,,,,:;;iiiiii;::::::,:::::iiiiiiiiiiiiii;:::::,,:;iiiiiiiiiii;
,,,,,,,::;;;;;::,,:;;;;;;;;;;:,,,,,,:;;:,,,,;#zxn##+##############++++******++++*i;:::,,,,,,::;iiiiiii;::::,,,:,,:iiiiiiiiiiiiii;::::::::;iiiiii;iiii;
,,,,,,:;;;;;;::,,,,,:;;;;;;;;:,,,,.,,;;:,,,,:*zxnz#++##############+++******++++*i;:::::::,::::;iiiiiii;::::,,:,,:iiiii;;iiiiiii;::,,,:::;iiii;::;;iii
,,:,::;;;;;;::,,,,,,::;;;;;;:,,,,,,,,:;:,,,,:i#nxn#+++##############+++****+#++#+*;:::,,::,::::;iiiiiiii;::::::::;iiiii;;iiiiiii;::,:,,,,:ii;:::::;;ii
,:;;;;;;;;;::,,,,,,,,,:;;;;;:,,,,,,,,:;;:,,,::+nxnz##+*+############+++****+++##+i;:::,,:,,,,,:;iiiiiiiii:::::::;iiiii;;;iiiiiii;::::,,,,;;;:,,,:::;ii
,:;;;;;;;;;::::::,,,,,,:;;;;:,,,,,,,,:;;:,,,,,;#nnz##+*+############++++********i;:::::::::::::;;iiiiiiii;::::;;iiii;;::;iiiiiii;::::::::;i;:,,,:::;ii
,;;;;;;;;;;;;;;;;::,,,::;;;;::,,,,,,,:;;:,,,,,:+nnz###++###########++++*********;;;:::::::::::::;;;iiiiiii;iiiiiiiii;;;:;iiiiiii;::::,,,:;;;:,,,,,::;i
:;;;;;;;;;;;;;;;;;;;;;;iiii;;:,,,,,,,,:;:,,,:::izzz################++++********i;;:::::,:::::::::::;;;iiiiiiiiiiiiii;;;:;iiiiiii;::::,,,:;;:,,,,,,:,:;
;;;;;;;;;;;;;;;;;;;;i;iiiiii;:,,,,,,,,:;:,,,,,,;+###################+++**+++***i;;:::::,:,,::::::::;::;iiiiiiiiiiiiiii;:;iiiiiii;::::,,::;;:,,,,,::,:;
;;;;;;;;;;;;;;;;;;;;;;iii;;i;;::,,,,,,:;;:,,,,,:i+#################++++*++####+i;;:::::::::::::::::;::;iiiii;iiiiiiiiii;;iiiiiii;:::::::;i;:,,,,,,::;;
;;;;;;;;;;;;;;;;;;;;;iiii;;i;;;:,,,,,,:;;:,,,,,:i+##################+++***++++*;;;;;;;::;;;;;::;;::;;:;iii;;::::;iiiiiiiiiiiiiii;::::,,,;;;:,,,,,,:;;;
;;;;;;;;;;;;;;:::;;;;iii;;;;i;;:,,::,,:;;:::::::;*##################++++******i::::::::::::::::::::;:,:;ii;:::::::;iiiiiiiiiiiii;:,:,,,:;;:,,,,,,,:;;;
;:::,::::;;;::,,:::::;i;;;:;ii;;:,::,,:;;::,,,::;*##################++++******i:;;:::::,:::::::::::;:,:;i;:::::::::;iiiiiiiiiiiii::::,,:;;:,,,,,,,:;;;
::,,,:::::::::,,::::;;;;:::;iii;::::,,,:;;:,:;;;i+###################+++******;:;;:::::::::::::::::;::;ii;::,,,:::,:;iiiiiiiiiiii;:;;::;i;::,,,,,:;;;;
::,,,::::,,,,:,,:::;;;;::::;;iii;:,,,,,:;;:,;*;;i+###################+++******;;;;;;;;:::::::::::::;;;iii;;:,,,::,,:;iiiiiiiiiii;::::,:;i;:::,,,,:;;;;
:::,,,::::,,,:::,,:;;i;::::;;iii;::,,,,:;;;;*i;ii+###############zz####+++****iiii;;;::::::::::;;;;iiiiii;;:,,,:::::;iiiiiiiiiii;::::,:;i;:,,,,,,:;;;:
:::::::::::,,,:::::;ii;::::;;iiii;::::,:;;;i#*i++#################zzzz###+++*iii*i;;;:::::::::::iiiiiii;;;;;:,,,,::::;iiiiiiiiiii::::::;i;:,,,,,:;;;::
,,::::::::::,,,::::;iii;::;;:;iii;;::::;iii+z+i###################zzz######+*iiiii;;;::::::::::;iiiiiii;;;;;;::,,::::::;iiiiiiiii;:::;;ii;:,,,,,:;;;:,
:::,::::,,:::,,::;;;iii;::;;::;;ii;::;;ii*+znz*+###################z#*ii***iiiiiii;;;;;;;;:;;::;iiiiiii;;;;;ii;;:::::::;iiiiiiiii:::;;iii;::,,,:;;;;:,
:::,::::,,:::,:::;iiii;:::;;:::;ii;;;;ii*#nxxn+*####################+iii;;;iiiiiiii;;::::::::::iiiiiii;;;;;;iii;::::::::;iiiiiiii;;iiiiii;:::::;;;;;:,
:::,::::::,::::::;iiii;:::;;:;;iiiiiiii*#nxMMx#*#########++++###+++++ii;;;:;iiiiiii;;:::::::::;iiiiii;:::;;;;ii;::::::::;iiiiiiiiiiiiiiiii;:,,:;;;;:,,
:::::::::::::::::;iiii;:::;iiiiiiiiii*+zxxMMMxz*+#######++++++++++****i;;:::;iiiiiiii;;::::;;;iiiiii;:,,,:;;;;;;::::::::;iiiiiiiiiiiii;;iii;:,;;;:::,,
::::::::::::::::;;iiii;;;ii*iiiiii*+#znxMMMMMMn*i+######++++++++++**+*i++i;;;i;iiiiiiii;;:;iiiiiiii;;:,,,,:;iiii;::::::;iiiiiiiiiiii;;;;;ii;;;;;;;::,,
::::::::::::::::;;iiiiiiiii*iiii*+#zxxxMMMMMMMn+ii+#####+++++++++++*+*i+nn#+ii;;iiiiiiii;;ii**iiii;;;:::,,,:;iiii;::::;iiiiiiiiiiiii;::::;iii;;;;;;::,
:::::;:::::;::::;;iiiiii****ii*+znxxMMMMMMMMMMx#*i*#####+++++++++++++*i*nxn#+iiiiiiiiiiiiii***iiii;;;:,::,::;iiiii;:::;iiiiiiiiiii;::::::;iii;;;;;;;;:
::::::;:::::;;;::;iii**i**ii*+#nxxMMMMMMMMMMMMMn*ii+#####++++++++++++iiizxnz###+++**iii**i******i;;::,,,,,,,:;iiii;;:;iiiiiiiiiii;::::;::;iii;;;;;;;;;
::::::;;:::::;;:;iii***ii**+znxxMMMMMMMMMMMMMMMx#*ii+####++++++++++#+ii;#xnzzzzzzz#+*iii*****iiii;:::,,,,,,,:iiiiii;;ii**iiiiiiii;:::::::;;ii;;;;;;;;;
::;;::;;;:::::;;iii**ii*+#znxxMMMMMMMMMMMMMMMMMMz*i;*+###++++++++++z+ii;+xnzzz##z###nz#****ii;;;;;:;;:::,,,::iiiiiiiiiiiiiiiiiiii;::::::::;ii;;;;;;;;;
::;;;;;;;;;;;;iii**ii**#znxxMMMMMMMMMMMMMMMMMMMMn+i;;*###+++++++++#z+ii;*nnzzzz#z###xxxn#*ii;;:::::;:::::::::;iiiiiiiiii;;iiiiiii;:::;:::::;i;;;;;:;;;
::::;;i;;;;;;iii*****#znxxMMMMMMMMMMMMMMMMMMMWMMx+*i;i+##++++++++#zz*ii;*nzzzzzzz#+*xxxxxn#*;;:::::::,,,,,,,,:;iiiiiiiii;iiiiiiii;::::::::;;i;;;;;;:::
::::;iiiiiiii***i**#znxMMMMMMMMMMMMMMMMMMMMMWWWMn+*i;;i+#+++++++#zz#*i;;inzzzzzzz#++xxxMMxxn#*;;:::;;::::,:::::;iiiiii*iii*i*iiiii;::::::;iiiiii;;;::,
:::;iiiiiii*****+#znxMMMMMMMMMMMMMMMMMMMMMMMWWWMz+*ii;;i+++**+++#zz+ii;;;##zzzzzz##+xxxxxxMxxn#*;;;i;::::::::::;;iiiii*****iiiiiii;;;;:::;iiiiii;;;;::
;;iiiiiiii****##znxMMMMMMMMMMMMMMMMMMMMMMMMMWWWMz+**ii;;i++**++#zz#*i;;;;##zzzzzz##+xxxxxxMMMxxz*::;;::::::::;:;;iiiiii****iiiiiii;;;;;:;;iiiiiii;i;;:
iiiiiiiiiii**#nxMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMn+*iii;;;i****+#z#*i;;;;;##zzzzzz##+xxxMxMxxxxMxzi;;::::,,:::::;iiiii;ii***iiiiiii:::;;;;iiiiii;iii;::
iiiiiiiiiii*+nxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMx+*ii;;;;;i**+###*ii;;;;*nzzzzzzz##+xxxxxxxxxxxxx*;;;:::,,::,:::iiii;;;ii***iiiii;:::;::;iiiii;;iiii;:
iiiiiiiiiii*zxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMz*ii;;;;;;i*###*ii;;;;iznzzzzzzzz##xxxxxxxxxxxxx#ii;:::,,:::::;iiii;;;;ii*iiiiiii;:::::;iiiii;:;iii;:
iii;;ii;;ii+nxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMn*ii;;;;;ii*+*ii;;;;;;+xnzzzzzzz###xxMMMxxxMxxxxzii;;;::::::;;ii**i;;;:;iiiiiiiii;;;::;iiiii;:::iii;:
i;;;;;;;;;i#xxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMM#*i******+**iii;;;;;izxnzzzzzzz###xxMMMMMMMMxxxn*i;::::::;iiiii**i;;;:;iiiiiiiii;::;;iiiiii;:::iii;:
;;;;;;;;;;izxxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxnnnxxn#+++++*ii;;;*nxxnnznzzzz##xxxMMMMMMMMMMx*i;::::::;iiiii**i;;;;i***iiiiii;::::iiiiiii;::iiii;
;;;;;;;;;;+nxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMx#*+#nnnz#++###*ii#xxxnzzzz###+zxMMMMMMMMMMMMx#i;;::::;iiii****i;;;i****iiiiii;:::;iiiiiii;:;;iii;
;;;;ii;;;i#xMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMxz#*ii*+#zznxxMxzzxxxxnz#z##++*zxMMMMMMMMMMMMxzi;;;;:;iiii*****i;;;;iiiiiiiiii;;::;iiiiii;;::;iii;
:;;;ii;;;inxMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMxxn#+****++####nxxxxxxnxnnnnnxxMMMMMMMMMMMMMni;;;:;;iii*****i;;;;;iiii**iiii;;;;iiiiiii;::::iii;
;;;;;i;;;+xxMMMMMMMMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMMMMMxz##znnnnz#+*iii*nxxxxxxnz#znxMMMMMMMMMMMMMMMx+;;;;;iiiiii****i;;;ii*i****iii;;;;iiiiii;:::::;iii
;;;;;;;;;+xMMMMMWWWMMMMWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMx#+*ii*#znxxxnn##xMMMMMx#+++#xxMMMMMMMMMMMMMMx#;;;;iiiiiii***ii;;ii*******iii;;;;iiiiii;:;;::;iii
;;;;;;;;i#xMMMMWWWWMMMMWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMxxnz#**ii*+#znxxMMMMMMx#+++zxxMMMMMMMMMMMMMMx#i;;ii**iiiii***i;;iii********i;;;iiiiiiii;:::::iii
;;;ii;;;izxMMMWWWWWMMMMWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMnnxxnnz#+*iii*#xxMMMMxz+++#xMMMMMMMMMMMMMMMx#iiiii*ii;;;i***iii*iii*******i;;iiiiii*ii;:::::;ii
:;;;;;;;inxMMMWWWWWMMMWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMx#i*++#znnnnz++#xMMMMMx#***+xMMMMMMMMMMMMMMMx#iiiii*ii;;;i******iiii*******i;;i*ii;i**ii;;:::;ii
;;;;;;;;*nxMWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMnz##*ii*+#nxxxMMMMMMMn+***+xMMMMMMMMMMMMMMMxziiiiiii;;;ii******iiiii******i;;i*ii;iiiiiii;;;;ii
;;;;i;;;*nxMMWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMxxMxnz+*ii*+#nMMMMMMn****+xMMMMMMMMMMMMMMMxziiiii;;;;iii******iiiii******i;iiii;:;iiiiii;::;ii
;;;;i;;i+nMMWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMx#*+znnnnz#+**#xMMMMMn****+xMMMMMMMMMMMMMMMxziiii;;;;;iii******i;;ii******iii*ii;:;iiiiii;:::;i
;;;;iii*#nMMWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMxz*****++znnnnxMMMMMMn****#xMMMMMMMMMMMMMMMMn*iii;;;;iiiiiii***i;;;ii*****iii**i;;iiiii*i;:::;i
;;;;iii#znMMWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMxxnn#+*ii*+#nMMMMMMMn****#xMMMMMMMMMMMMMMMMn*ii;;;;iii*iiii***i;;;iii*****ii*i;;iiiiiiiii;::ii
;;;;ii*znxMMWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMnnxxxxn#+*i*zxMMMMMn*ii*#xMMMMMMMMMMMMMMMMx*ii;;iiiiiii;;ii**ii;;ii*********iii**iiiiiiii;;;i
i;;;ii*xxxMMWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMM#**+znxxxnzznMMMMMMn*ii*#xMMMMMMMMMMMMMMMMx*ii;iiiiiii;;;;ii*ii;;ii*************ii;;i*iiiiiii
*iiiii+xxMMMWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMx#+****++znxMMMMMMMn****#xMMMMMMMMMMMMMMMMx+iiiiiiii;;;;;;iiiiiiiii************ii;;;;ii*iiiii
**iiiizxMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMxxxnz#+*i*+nMMMMMMx##++#xMMMMMMMMMMMMMMMMx+iiiiiiii;;;;;;;;iiiiiiii***********i;;;;;:;iiiiii
**iii*nMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMn#nxxxxnz++zMMMMMMMzz+#nMMMMMMMMMMMMMMMMMx#iiiiiiii;;;;;;;;iiiiiiii**********i;;;:::::;iiiii
***ii*nMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWMMMMMMMMMMMMMMMn+*+#znnMxxMMMMMMMMxnznMMMMMMMMMMMMMMMMMMMziiiiiiii;;;;;;;;iiiiiiii**********i;;;:::::;iiiii
***ii#xMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWMMMMMMMMMMMMMMn##+***+#nxMMMMMMMxnzxMMMMMMMMMMMMMMMMMMMziiiiiii;;;;;;;;;iiiiiiii*********ii;;;;;::::;iiii
***iizxMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWMMMMMMMMMMMMMnnxxn#+*i*nMMMMMMMxnzxMMMMMMMMMMMMMMMMMMMziiii;;;;;;;;;;;;;iiiiiii*******ii;;::;;;::::;;iii
i**i*nxMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMn+#nxMxnnnxMMMMMMMxnzxMMMMMMMMMMMMMMMMMMMziii;;;;;;;;;;;;;;;;iiiii*******i;;:::::::::,:::;;
***i+xMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMWWMMz+++#znxMWMMMMMMMxzzxMMMMMMMMMMMMMMMMMMMn*ii;;;;;;;;;;;;;;;;iiiii******i;;::::::::::::,,:;
**iizMMMWWWWWWWWWWWWWWWWWWWW@@WWWWWWWWWWWW@WWWWWWWWMMMMMWWMMxnz#+***#xMMMMMMMxzzxMMMMMMMMMMMMMMMMMMMn*iiiiiii;iii;;iii;iiiiii******ii;;;;;::::::::,:;;
**i*nMMMWWWWWWWWWWWWWWWWWWWW@@WWWWWWWWWWWWW@WWWWWWWWWWWWWWMMxznxxn#+#nMMMMMMMxzzxMMMMMMMMMMMMMMMMMMMx*iii;;;;;;iiiiiiiiiiiiii******iiii*iiiii;;;;;;;;;
*ii+xMMWWWWWWWWWWWWWWWWWWWWW@@WWWWWWWWWWWWWWWWWWWWWWWWWWWWWMx#+zxMMxxMMMMMMMMxzzxMMMMMMMMMMMMMWMMMMMx+ii;;;;;;;;;;;;;;;;;iiiii****ii;;;;;;:::::::,::;;
iii#xMMWWWWWWWWWWWWWWWWWWWWW@@@@WWWWWWWWWWWWWW@@WWWWWWWWWWWWMxz###znxxxMMMMMMxnzxMMMMMMMMMMMMMWMMMMMM+ii;;;;;;;;;;;;;;;;;iiiii*****ii;:::::::,,,,,,,:;
*iizMMMWWWWWWWWWWWWWWWWWWW@@@@@@WWWWWWWWWWWWWWWWWWWWWWWWWWWWWMnnnz####nMMMMMMxzzxMMMMMMMMMMMMMWMMMMMMzii;;;;;;;;;;;;;;;;iiiiiiii***ii;;;;::::,,,,,,,,;
iiizMMWWWWWWWWWWWWWWWWWWW@@@@@@@@@WWWWWWWWWWWWWWWWW@WWWWWWWWWx#znnzzz#nxMMMMMxzzxMMMMMMMMMMMMWWMMMMMMziiii;;;;;;;;;;;;;;iiiiiiii****iii;;::;::,,,,,:;;
*iinMMWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@WWWWWWWWWWW@@@@@WWWWWWWWMnzzzz#####zxMMMxzzxMMMMMMMMMMMMWWMMMMMMn*iiiii;;;;;;;;;iiiiiiiiiii*******ii;;;;:,,,:;;;;
*iinMWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@W@@WWWWW@@@@@@@WWWWWWxnz#######+++#nMMxnzxMMMMMMMMMMMMMWMMMMMMx*iiiii;;;;;;;;iiiiiiiiiiiii*******i;;::::,:;;;;;
*iinMWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@WW@@@@WWWWW@@@@@WWWMMxnz##+++##+++++#xMxnzxMMMMMMMMMMMWWWMMMMMMx+iiiii;;;;;;;;iiiiiiiiiiiiii******i;;::::::;;;;;
ii*nMWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@WWWW@@@@@@@WW@@@@WMxnzzz#+++####zzz#zxMxnzxMMMMMMMMMMWWWWWMMMMMM#iiiiii;;;;;;;iiiiiiiiiiii********i;;:::,,:;;;;;
ii*nMMWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@WWWWW@@@@@@@WWWWMMxnzzzz#++#znnnnnxxxMMxnzxMMMMMMMMMMWWWWWWMMMMMziiiiii;;;;;;iiiiiiiiiiiii**i******i;;::::;;;;;;
ii*nMMWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@WWWWW@@@@@@@@WWWxxnzzzzz#+++######nMMMMxnzxMMMMMMMWWWWWWWWWMMMMMziiiiiii;;;;iiiiiiiiiiiiiiiiiiii***ii;:::;;;;;;;
ii+xMMWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@WWWWW@@@@@@@WWWMnnnzzzzz##++++++++#xMMMxnzxMMMMMMMMWWWWWWWWMMMMMn*iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii***ii;:;;;;;;;;
ii+xMMWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@WWWWWWWW@@@WWWWWWMnnzzzzzzz#+++++++#zxMMMxnzxMMMMMMMMWWWWWWWWWMMMMx*i;iiiiiiiiiiiiiiiiiiiiiiiiii;;ii**iiiiiii;;;:;
ii+xMMWWWWWWWWWWWWWWWWWWWWWWWWW@@@@@WWWWWWWWWWWWWWWWWMnzzzzzzz###+######nMMMMxnzMMMMMMMMMWWWWWWWWWMWMMn*;;iiiiiiiiiiiii;iiiiiiiiiiii;;;i**iiiiiii;;;:;
ii+nMMWWWWWWWWWWWWWWWWWWWWWWWWWW@@@WWWWWWWWWWWWWWWWWWMnnzzzzzz#########zxMMMMxnzMMMMMMMMMWWWWWWWWWWWMMzi;;;iiiiiiiiiiii;;iiiiiiii*ii;;;iiiiiiiii;;:::;
ii+nxMWWWWWWWWWWWWWWWWWWWWWWWWWW@@WWWWWWWWWWWWWWWWWWWMnnzzzzzz#++++++++zxMMMMxnnMMMMMMMMMWWWWWWWWWWWMMni;;;;;iiiiiiii;;;;;iiiiiiiiiii;;;iiiiiii;;::,,:
ii+nxMWWWWWWWWWWWWWWWWWWWWWWWWWW@@WWWWWWWWWWWWWWWWWWWMxnzzzzzz#++++++##zxMMMMxnnMMMMMMMWWWWWWWWWWWWWWMx*i;;;;;iiiiii;;;;;;iiiiiiiiiii;;;;;iiiii;:::,,:
ii+xMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMxnzzzzzzz####zzzzxMMMMMnnnMMMMMMMWWWWWWWWWWWWWWMx+i;;;;;iiiiii;;;;;;iiiiiiiiiii;;;;;;iiii;:::,,:
ii#MMWWWWWWWWWWWWWWWWWWWWWWWWWWW@WWWWWWWWWWWWWWWWWWWWWxnzzzzzzz###zzz##xMMMMMnnnMMMMMMMWWWWWWWWWWWWWWMM#ii;;;;iiiiii;;;;;iiiiiiiiiiii;i;;;;;iii::::::;
i*nMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWxnzzzzzz##+++#++#xMMMMMnznMMMMMWWWWWWWWWWWWWWWWMMn+i;;;;iiiiii;;;;;iiiiiiiiiiii;;;;;;;iii;::::::
i*xMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW@WWWWWWWWWWWWWWxnzzzzzzz#++###znMMMMMMxnnMMMMMWWWWWWWWWWWWWWWWMMMn#ii;;iiiiiiii;;iiiiiiiiiiii;;;ii;iiiii;;::::;
i+xMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW@WWWWWWWWWWWWWWWxnnzzzzzz###zznxMMMMMMMxnnMMMMWWWWWWWWWWWWWWWWWWWMMxz*iiiiiiiiiii;iiiiiiiiiiii;;;;;;iiiiii;:::::
i*xMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW@@WWWWWWWWWWWWWWxnnnnzznnnxxMWWWWMMMMMMnnnMMMMWWWWWWWWWWWWWWWWWWWWWWMxz#+*iiiiiiiiiiii***iiiii;;;;iiiiiiii;;:::;
i*nMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMxnnnxxxMMW@@@@WWWMMMMMnnnMMMMWWWWWWWWWW@@WWWWWWWWWWWWWWMx#*ii;i;ii**+#+*iiiii;;;iii**iiiiii;::;
iizxMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW@WWWWWWWWWWWWWWWWWWWWMMMWWWWW@WWWWWMMMMMMnnnMMMMWWWWWWWWWW@@@WWWWWWWWWWWWWWWMx#*iiii*##z#+iiiiiii;iii***iiiiiii;::
ii+xMWWWWWWWWWWWWWWWWWWWWWWWWWWWW@@@@WWWWWWWWWWWWWW@WW@@@@@WWWWWW@@@@WWWMMMMMnnxMMMWWWWWWWWWW@@@WWWWWWWWWWWWWWWWWWMn#**+#znz#*iiiiiii;;ii***iiiiiii;::
ii*nMWWWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@WWWWWWWWWWWWWW@@@@@@@WWWWWWW@@@@WWWMMMMMnzxMMWWWWWWWWWWW@@@WWWWWWWWW@@@@@@WWWWWxnzzznzz#+**iiiii;iii**i;;iiiii;::
iii#MMWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@WWWWWWWWWWWWWWWW@@@@@@WWWWWW@@WWWWWWMMMMnzxMWWWWWWWWWWWW@@@WWWWWWWW@@@@@@@@W@@WMxnnnnz##+++++++***iiiii;;;iiiii;;
iii+xMWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@WWWWWWWWMxWMMMW@@@@W@@WWWWMW@@WWWWWMMMMMnnxMWWWMWWWWWWWW@@@@WWWWWW@@@@@@@@@@@@WMxnnnzzz###########++**i;;;;;iiiii
iii*nMMWWWWWWWWWWWWWWWWWWWWW@@@@@@WWWWWWW@@WMnnMMMMW@WWWW@@WWWWMW@@@@@WWWMMMMnnxMWMWWWWWWWWWW@@@@@@@WW@@@@@@@@@@@@@WMxnnnzzzzzzzzz#########++*;;;iiiii
*iii#xMWWWWWWWWWWWWWWWWWWW@@W@WWWWWWWWWW@W@WMxxWWWW@@@WWW@@WWWWWW@@WWWWWWMMMMxnxMMMWWWWWWWWWW@@@@@@@@@@@@@@@@@@@@@@WMxnnnzzzzzzzzzzz###+######++*iiiii
*iiiizxMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWW@@@@@WWWW@@@@@@@@@@@@@WWWWW@@WMMWWWMMMMxnxMMWWWWWWWWWW@@@@@@@@@@@@@@@@@@@@@@@WMxnnnzzzzzzzzzzzz##+*ii*+####+iii*
iiii;izxMMWWWWWWWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@@@@@@WWWWW@@@WWWWWMMMMxnxMMMMWMxnMWWW@@@@@@@@@@@@@@@@@@@@@@@WMxnnnzzzzzzzzzzzz##+*ii;;;ii**iii*
**iii;i#nxMMWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@@@@@@@@@@@WWWWWW@@WWWWWWMMMnnxMMMMMnzzzMWW@@@@@@@@@@@@@@@@@@@@@@@WMxnnnzzzzzzzzzzzz####+*i;;;;;i;ii*
**iii;;;i*##znnnxxxxxxMMWWWWWWWW@@@@@@@@@@@@@@@@@@@@@@@@@@@@@WWWWW@WWWWWWWMMMnzxMMMMMnzzzMWW@@@@@@@@@@@@@@@@@@@@@@@WMxnnnzzzzzzzzzzzz###z##+*i;;;;;;i*
**iiii;;;;;;iiiiiiiii*#xxxWWWWW@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@WWWW@@@@@@WWWWMMnzxMMMMMxnnxWWWW@@@@@@@@@@@@@@@@@@@@@@WMxnnnnzzzzz#zzzzz#+*+#zzz#*;;;i;;i
**iiiiiiiiiiiiiiiiiiii+xxnWWWW@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@WWWW@@@@@@@WWWMMnnxMMMMMMMMWWWWMxMW@@@@@@@@@@@@@@@@@@@@Wxnnnnzzzzz#zzzzzz#*ii*#zz#+iiiiii
***iiiiiiiiiiiiiiiiiii+xnnWWWWW@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@WWW@@@@@@@@WWWMMnnxMMMMMWWWWWWWn++zxWW@@@@@@@@@@@@@@@@@WMxnnnzzzzzzzzz##z#+*iii*#zz#+iiii
***iiiiiiiiiiiiiiiiiii+xnnWWWWW@@@WWWW@@@@@@@@@@@@@@@@@@@@@@@@WW@@@WW@@@WWWMMnzxMMWWWWWWWWWWn*ii*#nMWWW@@@@@@@@@@@@@@WMxnnnzzzzzzzz++#zz#+iiii*#z#+*ii
***iiiiiiiiiiiiiiiiiii#xnnWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@@@@@@WW@@@WW@@WWWWMMnzxMWWWWWWWWWWWn*iiiii+znMWWWWWW@@@@@@@@WWMxxnnzzzzzzz#*i+zz#+iiiii+#+*ii
***iiiiiiiiiiiiiiiiiii#xnnWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@@@@@WW@@@WW@@WWWWWMnzxMWWWWWWWWWWWn*iiii;;ii+#nxMMWWWW@@@@@WWWWMMxnnz#zzz#+ii*#z#+iiiiii**ii
***iiiiiiiiiiiiiiiiiii#xnnWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@@@W@@@WWWWWWWWWMnzxWWWWWWWWWWWWn*iiiii;;;iii*+#nxMWWWWWWWWWWWWWMMn+*+zz#*iii#zz+i;iiiiiii
***iiiiiiiiiiiiiiiiiii#xnnMWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@@WMxxxMWWMMnzxWWWWWWWWWWWWz*ii;;;;;;ii;;iii*+#nxMMWWWWWWWWWWn*ii+#+*i;ii+z#*iiiiiiii
***iiiiiiiiiiiiiiiiiii#xnnMWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@@@WxxxxMWWWMnzxMWWWWWWWWWWWziii;;;;;;iii;;iiiiii*+#nxMWWWWWWM#iiii***i;iii***i;;iiiii
***iiiiiiiiiiiiiiiiiiizxznMWWWWWWWWWWWWWWWWWWWWW@@WWW@@@@@@@@@@@@@@WxxxxxMWWMnzxMWWWWWWWWWWWn*ii;;;;;;ii;;;;;;i;;;;ii*+#zxMMxz*i;iiiii;;iiiiiii;;iiiii
***iiiiiiiiiiiiiiiiiiizxznMWWWWWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@WxnxxxMWWMnzxMWWWWWWWWWWWn*iii;;;;;iii;;;;;;;;;;;;;;ii*+++*i;;iiii;;iiiiiiiiiiiiiii
***iiiiiiiiiiiiiiiiiiiznznMWWWWWWWWWWWWWWWWWWWWWWW@@W@@@@@@@@@@@@@@WxnnxxMWWMnzxMWWWWWW@WWWWx*iii;;;;;;i;;;;;;;;;;;;;;;;;;iiiiiiiiiii;;iiiiiiiiiiiiiii
***iiiiiiiiiiiiiiiiiiiznznMWWWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@xnnxxxWWMnzxMWWWWWW@WWWWM+ii;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iiiiiiiiiiiiiiiiiiiiiiii
***iiiiiiiiiiiiiiiiii*zzzxMWWWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@xnnxxxMWMnzxMWWWWWWWWWWWM#ii;;;;;;;;;;;;;;;;;;;;;;;;;;;;;iiiiiiiiiiiiiiiiiiiiiiiii
****iiiiiiiiiiiiiiiii*nznxMWWWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@xnnnxxMWMnzxMWWWWWWWWWWWM#iii;;;;;;;;;;;;;;;;;;;;;;;;;;;;iiiiiiiiiiiiiiiiiiiiiiiii
*****iiiiiiiiiiiiiiii*zznMMWWWWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@MnnnnxMWMnzxMWWWWWWW@@WWW#iii;;;;;;;;;;;;;;;;;;;;;;;;;;;iiiiiiiiiiiiiiiiiiiiiiiiii
******iiiiiiiiiiiii*i*z#xMWWWWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@MnnnnxxMMnzxWWWWWWWWW@WWW#iii;;;;;;;;;;;;;;;;;;;;;;;;;;;iiiiiiiiiiiiiiiiiiiiiiiiii
******iiiiiiiiiiiii*i*zzxMWWWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@@MnnnnxxMMnzxWWWWWWWW@@@WW#iii;;;;;;;;;;;;;;;;;;;;;;;;;;;iiiiiiiiiiiiiiiii;iiiiiiii
******iiiiiiiiiii*iii+zzMMWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@@@@@MznnnnxxxnnxMWWWWWW@@@WWWziii;;;;;;;ii;;;;;;;;;;;;;;;;;iiiiiiiiiiiiiiiiiiiiiiiiiii
******iiiiiiiiiiiiiii+znMMWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@@@@@MzznnnnxxnnxMWWWWWW@@@WWMziiii;;;;ii;i;;;;;;;;;;;;;;;;;;;;iiiiiiiiiiiiiiiiiiiiiiii
***iiiiiiiiiiiiiiiiii#znMMWWWWWWWWWWWWWWWWWWWWW@WW@@@@@@@@@@@@@@@@@@MzznnnnnxnzxMWWWWWW@@WWWMziiii;;;;;;;i;;;;;;;;;;;;;;;;;;;;iiiiiiiiiiiiiiiiiiiiiiii
***iiiiiiiiiiiiiiiiii#zxMMWWWWWWWWWWWWWWWWWWW@WWWWW@@@@@@@@@@@@@@@@@MzznnnnnnnzxMWWWMMWWWWWWWz*iii;;i;iiiii;;;;;;;;;;;;;;;;;;;iiiiiiiiiiiiiiiiiiiiiiii
***iiiiiiiiiiiiiiiiiiz#xMMWWWWWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@MzzznnnnnnzMMWWMxnMWWWWWWn*iiiiii;;i;ii;;;;;;;;;;;;iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
+++++++++***********+zzxMMMMWWWWWWWWWWMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWMnznnnnnxnnMMMMMxxMWWWWWMn+*******************************************************
Zoom out""",'yellow'))